//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComponentToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComponentToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;InputItems&quot;:{&quot;15b7afe5-d0d0-43e1-b894-34fcfe3be384&quot;:[{&quot;ObjectGuid&quot;:&quot;d1a28e95-cf96-4936-bf34-8bf142d731bf&quot;,&quot;initString&quot;:null,&quot;Index&quot;:0},{&quot;ObjectGuid&quot;:&quot;ccfd6ba8-ecb1-44df-a47e-08126a653c51&quot;,&quot;initString&quot;:null,&quot;Index&quot;:1},{&quot;ObjectGuid&quot;:&quot;f44b92b0-3b5b-493a-86f4-fd7408c3daf3&quot;,&quot;initString&quot;:null,&quot;Index&quot;:0},{&quot;ObjectGuid&quot;:&quot;95992b33-89e1-4d36-bd35-2754a11af21e&quot;,&quot;initString&quot;:null,&quot;Index&quot;:0}],&quot;16ef3e75-e315-4899-b531-d3166b42dac9&quot;:[{&quot;ObjectGuid&quot;:&quot;56b92eab-d121-43f7-94d3-6cd8f0ddead8&quot;,&quot;initString&quot;:null,&quot;Index&quot;:0},{&quot;Obje [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quickwires {
            get {
                return ResourceManager.GetString("quickwires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResetIcons_24 {
            get {
                object obj = ResourceManager.GetObject("ResetIcons_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
