//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistentDataEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersistentDataEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComponentIcon_24 {
            get {
                object obj = ResourceManager.GetObject("ComponentIcon_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComponentToolkitIcon_128 {
            get {
                object obj = ResourceManager.GetObject("ComponentToolkitIcon_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ComponentToolkitIcon_24 {
            get {
                object obj = ResourceManager.GetObject("ComponentToolkitIcon_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditIcon_24 {
            get {
                object obj = ResourceManager.GetObject("EditIcon_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ParamControlIcon_24 {
            get {
                object obj = ResourceManager.GetObject("ParamControlIcon_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ParametersIcon_24 {
            get {
                object obj = ResourceManager.GetObject("ParametersIcon_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuickwireIcon_24 {
            get {
                object obj = ResourceManager.GetObject("QuickwireIcon_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;InputItems&quot;:{&quot;04d3eace-deaa-475e-9e69-8f804d687998&quot;:[{&quot;ObjectGuid&quot;:&quot;bb59bffc-f54c-4682-9778-f6c3fe74fce3&quot;,&quot;initString&quot;:null,&quot;Index&quot;:0},{&quot;ObjectGuid&quot;:&quot;9fa1b081-b1c7-4a12-a163-0aa8da9ff6c4&quot;,&quot;initString&quot;:null,&quot;Index&quot;:0},{&quot;ObjectGuid&quot;:&quot;9d2583dd-6cf5-497c-8c40-c9a290598396&quot;,&quot;initString&quot;:null,&quot;Index&quot;:0},{&quot;ObjectGuid&quot;:&quot;75f4b0fd-9721-47b1-99e7-9c098b342e67&quot;,&quot;initString&quot;:null,&quot;Index&quot;:0},{&quot;ObjectGuid&quot;:&quot;75f4b0fd-9721-47b1-99e7-9c098b342e67&quot;,&quot;initString&quot;:null,&quot;Index&quot;:1},{&quot;ObjectGuid&quot;:&quot;9d8dec9c-3fd1-481c-9c3d-75ea5e15 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quickwires {
            get {
                return ResourceManager.GetString("quickwires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResetIcons_24 {
            get {
                object obj = ResourceManager.GetObject("ResetIcons_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
